name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Explorer Challenge
      id: test-explorer-challenge
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Explorer Challenge
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-EXPLORER-CHALLENGE_RESULTS: "${{steps.test-explorer-challenge.outputs.result}}"
      with:
        runners: test-explorer-challenge
